### ISSUE TITLE
Cannot find module '@babel/plugin-transform-block-scoping'

### ISSUE THREAD

**Issue by raido** [ef4/ember-auto-import#238]
After upgrading from v1.3.0 -> v1.5.2 I get error from ember-data v3.10.0 `stripped-build-plugins.js` file that it fails to require `@babel/plugin-transform-block-scoping` when trying to `ember serve` the app.

**Comment by ef4** [comment]
This looks like an ember-data bug. It's trying to resolve `@babel/plugin-transform-block-scoping` but doesn't list that package in its dependencies.

The bug may only have appeared when you did an unrelated upgrade (of ember-auto-import), because node will allow things like this to work "by accident" as long as some peer of ember-data happens to already depend on `@babel/plugin-transform-block-scoping`.
